-- Seed: College Tour Trips — 8 colleges
-- Paste into Supabase SQL Editor and run once

DO $$ DECLARE uid uuid;
BEGIN SELECT id INTO uid FROM auth.users LIMIT 1;

-- 1. University of Virginia (Charlottesville)
INSERT INTO trips (title, destination, start_date, end_date, passcode, form_data, itinerary_data, created_by, user_id, is_published, visibility, description, tags) VALUES (
  'UVA Campus Tour: Charlottesville Weekend', 'Charlottesville, VA', '2026-04-03', '2026-04-05', '1234',
  '{"destination":{"name":"Charlottesville, VA"},"start_date":"2026-04-03","end_date":"2026-04-05","group_members":[{"name":"Parent","type":"adult"},{"name":"Student","type":"child","age":17}],"budget_level":"mid","vibes":["culture"],"travel_theme":"college-tour"}'::jsonb,
  '{"title":"UVA Campus Tour: Charlottesville Weekend","days":[
    {"id":"day-1","trip_id":"t","date":"2026-04-03","day_number":1,"title":"UVA Campus & The Lawn","slots":[
      {"id":"s-1-1","day_id":"day-1","slot_type":"morning","status":"open","options":[
        {"id":"o-1-1-1","slot_id":"s-1-1","title":"Official UVA Campus Tour","description":"Student-led 90-min tour starting at the Rotunda — Thomas Jefferson''s iconic design, The Lawn rooms, and academic villages.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":90,"location":{"name":"The Rotunda, UVA"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"The Rotunda and Lawn are UNESCO World Heritage — one of the most beautiful campuses in America"},
        {"id":"o-1-1-2","slot_id":"s-1-1","title":"Bodo''s Bagels Breakfast","description":"UVA students'' obsession — fresh bagels with cream cheese, egg sandwiches. Cash only, always a line.","category":"food","estimated_cost_per_person":6,"duration_minutes":20,"location":{"name":"Bodo''s Bagels, The Corner"},"weather_sensitivity":"indoor","ai_generated":true,"why_this_fits":"Every UVA student eats here — it''s a rite of passage"}]},
      {"id":"s-1-2","day_id":"day-1","slot_type":"afternoon","status":"open","options":[
        {"id":"o-1-2-1","slot_id":"s-1-2","title":"The Corner & University Bookstore","description":"Walk UVA''s commercial strip — bookstore for merch, Littlejohn''s deli, and the student hangout scene.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":90,"location":{"name":"The Corner, University Ave"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"See where students actually spend their time"},
        {"id":"o-1-2-2","slot_id":"s-1-2","title":"Monticello — Jefferson''s Home","description":"Thomas Jefferson''s hilltop estate — guided tour of the house, gardens, and the complicated history.","category":"attraction","estimated_cost_per_person":28,"duration_minutes":120,"location":{"name":"Monticello"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"Jefferson founded UVA — see where it all started"}]},
      {"id":"s-1-3","day_id":"day-1","slot_type":"evening","status":"open","options":[
        {"id":"o-1-3-1","slot_id":"s-1-3","title":"Dinner on the Downtown Mall","description":"Charlottesville''s pedestrian mall — C&O Restaurant, The Whiskey Jar, or farm-to-table at Fleurie.","category":"food","estimated_cost_per_person":25,"duration_minutes":90,"location":{"name":"Downtown Mall, Charlottesville"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"One of the best small-town dining scenes in Virginia"},
        {"id":"o-1-3-2","slot_id":"s-1-3","title":"Walk Grounds at Sunset","description":"UVA calls it ''Grounds'' not ''campus'' — the Rotunda lit up at night is magical.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":30,"location":{"name":"The Lawn, UVA"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"The Lawn at twilight is when you fall in love with UVA"}]}
    ]}],"hiddenGems":[{"day_number":1,"tip":"Ask the tour guide about the ''secret societies'' — UVA has 7 of them and their symbols are hidden all over Grounds.","location":"Various locations on Grounds"}]}'::jsonb,
  'VYBR', uid, true, 'public', 'Weekend UVA campus tour: The Rotunda, Jefferson''s Lawn, Bodo''s Bagels, Monticello, and Charlottesville''s Downtown Mall.',
  ARRAY['uva', 'university-of-virginia', 'charlottesville', 'virginia', 'college', 'college-tour', 'campus']
);

-- 2. Duke University (Durham, NC)
INSERT INTO trips (title, destination, start_date, end_date, passcode, form_data, itinerary_data, created_by, user_id, is_published, visibility, description, tags) VALUES (
  'Duke Campus Tour: Durham & the Triangle', 'Durham, NC', '2026-04-10', '2026-04-12', '1234',
  '{"destination":{"name":"Durham, NC"},"start_date":"2026-04-10","end_date":"2026-04-12","group_members":[{"name":"Parent","type":"adult"},{"name":"Student","type":"child","age":17}],"budget_level":"mid","vibes":["culture"],"travel_theme":"college-tour"}'::jsonb,
  '{"title":"Duke Campus Tour: Durham & the Triangle","days":[
    {"id":"day-1","trip_id":"t","date":"2026-04-10","day_number":1,"title":"Duke Campus & Chapel","slots":[
      {"id":"s-1-1","day_id":"day-1","slot_type":"morning","status":"open","options":[
        {"id":"o-1-1-1","slot_id":"s-1-1","title":"Official Duke Campus Tour","description":"Student-led tour from the admissions office — Duke Chapel, West Campus Gothic architecture, Duke Gardens.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":90,"location":{"name":"Duke University West Campus"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"Duke''s Gothic campus is one of the most impressive in the country"},
        {"id":"o-1-1-2","slot_id":"s-1-1","title":"Coffee at Cocoa Cinnamon","description":"Durham''s best coffee shop — third-wave espresso, Mexican hot chocolate, and churros.","category":"food","estimated_cost_per_person":6,"duration_minutes":20,"location":{"name":"Cocoa Cinnamon, Lakewood"},"weather_sensitivity":"indoor","ai_generated":true,"why_this_fits":"Duke students'' go-to off-campus coffee"}]},
      {"id":"s-1-2","day_id":"day-1","slot_type":"afternoon","status":"open","options":[
        {"id":"o-1-2-1","slot_id":"s-1-2","title":"Sarah P. Duke Gardens","description":"55 acres of stunning gardens — terraces, a Japanese garden, and the Asiatic Arboretum. Free.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":60,"location":{"name":"Duke Gardens"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"One of the most beautiful university gardens in America"},
        {"id":"o-1-2-2","slot_id":"s-1-2","title":"UNC-Chapel Hill Visit (30 min away)","description":"Drive to nearby UNC — The Old Well, Franklin Street, the rival campus. Compare and contrast.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":150,"location":{"name":"UNC-Chapel Hill"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"Duke and UNC are 8 miles apart — see both on one trip"}]},
      {"id":"s-1-3","day_id":"day-1","slot_type":"evening","status":"open","options":[
        {"id":"o-1-3-1","slot_id":"s-1-3","title":"Dinner in Downtown Durham","description":"Durham''s food scene is incredible — Mateo (tapas), M Kokko (ramen), or Dame''s Chicken & Waffles.","category":"food","estimated_cost_per_person":20,"duration_minutes":60,"location":{"name":"Downtown Durham"},"weather_sensitivity":"indoor","ai_generated":true,"why_this_fits":"Durham''s food scene punches way above its weight"},
        {"id":"o-1-3-2","slot_id":"s-1-3","title":"Duke Bookstore & Cameron Indoor","description":"Pick up Blue Devils merch and peek at Cameron Indoor Stadium — the cathedral of college basketball.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":30,"location":{"name":"Duke University Store / Cameron Indoor"},"weather_sensitivity":"indoor","ai_generated":true,"why_this_fits":"Cameron Indoor is sacred ground for basketball fans"}]}
    ]}],"hiddenGems":[{"day_number":1,"tip":"Walk through the Duke Lemur Center website and book a tour — it''s the world''s largest sanctuary for lemurs and totally unique to Duke.","location":"Duke Lemur Center"}]}'::jsonb,
  'VYBR', uid, true, 'public', 'Weekend Duke campus tour: Gothic chapel, Duke Gardens, UNC-Chapel Hill side trip, Durham food scene, and Cameron Indoor.',
  ARRAY['duke', 'duke-university', 'durham', 'north-carolina', 'college', 'college-tour', 'campus', 'unc']
);

-- 3. University of Colorado Boulder
INSERT INTO trips (title, destination, start_date, end_date, passcode, form_data, itinerary_data, created_by, user_id, is_published, visibility, description, tags) VALUES (
  'CU Boulder Tour: Mountains & Campus Life', 'Boulder, CO', '2026-04-17', '2026-04-19', '1234',
  '{"destination":{"name":"Boulder, CO"},"start_date":"2026-04-17","end_date":"2026-04-19","group_members":[{"name":"Parent","type":"adult"},{"name":"Student","type":"child","age":17}],"budget_level":"mid","vibes":["nature","culture"],"travel_theme":"college-tour"}'::jsonb,
  '{"title":"CU Boulder Tour: Mountains & Campus Life","days":[
    {"id":"day-1","trip_id":"t","date":"2026-04-17","day_number":1,"title":"CU Campus & Flatirons","slots":[
      {"id":"s-1-1","day_id":"day-1","slot_type":"morning","status":"open","options":[
        {"id":"o-1-1-1","slot_id":"s-1-1","title":"Official CU Boulder Campus Tour","description":"Tour starts at the admissions center — Norlin Library, Farrand Field with Flatirons backdrop, and the Hill.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":90,"location":{"name":"CU Boulder campus"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"The Flatirons towering behind campus make this the most scenic college setting in America"},
        {"id":"o-1-1-2","slot_id":"s-1-1","title":"Breakfast at The Buff","description":"Boulder breakfast institution — green chile eggs, pancakes, and mountain views from the patio.","category":"food","estimated_cost_per_person":14,"duration_minutes":30,"location":{"name":"The Buff, Boulder"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"Where CU students go for birthday breakfast"}]},
      {"id":"s-1-2","day_id":"day-1","slot_type":"afternoon","status":"open","options":[
        {"id":"o-1-2-1","slot_id":"s-1-2","title":"Hike the Flatirons (Royal Arch Trail)","description":"Moderate 3.4-mile hike to a natural stone arch with panoramic views of Boulder and the plains.","category":"adventure","estimated_cost_per_person":0,"duration_minutes":150,"location":{"name":"Chautauqua Park / Royal Arch"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"CU students hike these trails between classes — it''s that close"},
        {"id":"o-1-2-2","slot_id":"s-1-2","title":"Pearl Street Mall Walk","description":"4-block pedestrian mall — street performers, indie shops, restaurants, and Boulder''s social center.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":90,"location":{"name":"Pearl Street Mall"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"The heart of Boulder''s college town culture"}]},
      {"id":"s-1-3","day_id":"day-1","slot_type":"evening","status":"open","options":[
        {"id":"o-1-3-1","slot_id":"s-1-3","title":"Dinner at The Kitchen","description":"Boulder''s community restaurant — locally sourced, family-style dishes. The original before it became a chain.","category":"food","estimated_cost_per_person":30,"duration_minutes":60,"location":{"name":"The Kitchen, Pearl Street"},"weather_sensitivity":"indoor","ai_generated":true,"why_this_fits":"Boulder pioneered farm-to-table — this is where it started"},
        {"id":"o-1-3-2","slot_id":"s-1-3","title":"Colorado School of Mines Side Trip (45 min)","description":"Drive to Golden to see the engineering-focused Mines campus — smaller, STEM-focused alternative.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":90,"location":{"name":"Colorado School of Mines, Golden"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"If considering STEM, Mines is 45 min away and worth comparing"}]}
    ]}],"hiddenGems":[{"day_number":1,"tip":"Folsom Field (CU''s football stadium) has the best mountain views of any college stadium — walk in for free when there''s no game.","location":"Folsom Field, CU Boulder"}]}'::jsonb,
  'VYBR', uid, true, 'public', 'Weekend CU Boulder campus tour: Flatirons hike, Pearl Street, mountain campus, Colorado School of Mines side trip.',
  ARRAY['cu-boulder', 'university-of-colorado', 'boulder', 'colorado', 'college', 'college-tour', 'campus', 'colorado-school-of-mines']
);

-- 4. USC (Los Angeles)
INSERT INTO trips (title, destination, start_date, end_date, passcode, form_data, itinerary_data, created_by, user_id, is_published, visibility, description, tags) VALUES (
  'USC Campus Tour: Trojans & LA Life', 'Los Angeles, CA', '2026-04-24', '2026-04-26', '1234',
  '{"destination":{"name":"Los Angeles, CA"},"start_date":"2026-04-24","end_date":"2026-04-26","group_members":[{"name":"Parent","type":"adult"},{"name":"Student","type":"child","age":17}],"budget_level":"mid","vibes":["culture","food"],"travel_theme":"college-tour"}'::jsonb,
  '{"title":"USC Campus Tour: Trojans & LA Life","days":[
    {"id":"day-1","trip_id":"t","date":"2026-04-24","day_number":1,"title":"USC Campus & DTLA","slots":[
      {"id":"s-1-1","day_id":"day-1","slot_type":"morning","status":"open","options":[
        {"id":"o-1-1-1","slot_id":"s-1-1","title":"Official USC Campus Tour","description":"Student-led tour from the admissions center — Tommy Trojan, Doheny Library, the Village, and Exposition Park.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":90,"location":{"name":"USC University Park Campus"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"USC''s campus is a palm-tree-lined oasis in the middle of LA"},
        {"id":"o-1-1-2","slot_id":"s-1-1","title":"Brunch at Nickel Diner","description":"DTLA breakfast spot — maple bacon donuts, chicken & waffles, and strong coffee.","category":"food","estimated_cost_per_person":16,"duration_minutes":30,"location":{"name":"Nickel Diner, Downtown LA"},"weather_sensitivity":"indoor","ai_generated":true,"why_this_fits":"Popular with USC students heading downtown"}]},
      {"id":"s-1-2","day_id":"day-1","slot_type":"afternoon","status":"open","options":[
        {"id":"o-1-2-1","slot_id":"s-1-2","title":"USC Village & Bookstore","description":"New student hub — dining, study spaces, and the USC bookstore for Trojan merch.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":60,"location":{"name":"USC Village"},"weather_sensitivity":"indoor","ai_generated":true,"why_this_fits":"See where students live and hang out"},
        {"id":"o-1-2-2","slot_id":"s-1-2","title":"UCLA Side Trip (30 min)","description":"Drive to Westwood to see the rival campus — Royce Hall, Bruin Walk, and the Sculpture Garden.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":150,"location":{"name":"UCLA, Westwood"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"Compare USC and UCLA — LA''s two great universities 12 miles apart"}]},
      {"id":"s-1-3","day_id":"day-1","slot_type":"evening","status":"open","options":[
        {"id":"o-1-3-1","slot_id":"s-1-3","title":"Grand Central Market Dinner","description":"Historic DTLA food hall — Eggslut, tacos, Thai, and artisan coffee all under one roof.","category":"food","estimated_cost_per_person":15,"duration_minutes":45,"location":{"name":"Grand Central Market"},"weather_sensitivity":"indoor","ai_generated":true,"why_this_fits":"LA''s most diverse food hall — 5 minutes from USC"},
        {"id":"o-1-3-2","slot_id":"s-1-3","title":"Exposition Park Museums","description":"Natural History Museum, Science Center (free), and the upcoming Lucas Museum — all next to USC.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":120,"location":{"name":"Exposition Park"},"weather_sensitivity":"indoor","ai_generated":true,"why_this_fits":"World-class museums literally across the street from campus"}]}
    ]}],"hiddenGems":[{"day_number":1,"tip":"The LA Memorial Coliseum (2028 Olympics venue) is on the USC campus — you can walk in and see the Olympic torch for free.","location":"LA Memorial Coliseum"}]}'::jsonb,
  'VYBR', uid, true, 'public', 'Weekend USC campus tour: Trojan campus, USC Village, UCLA side trip, Grand Central Market, and Exposition Park museums.',
  ARRAY['usc', 'university-of-southern-california', 'los-angeles', 'california', 'college', 'college-tour', 'campus', 'ucla']
);

-- 5. Emory University (Atlanta)
INSERT INTO trips (title, destination, start_date, end_date, passcode, form_data, itinerary_data, created_by, user_id, is_published, visibility, description, tags) VALUES (
  'Emory Campus Tour: Atlanta & Southern Charm', 'Atlanta, GA', '2026-05-01', '2026-05-03', '1234',
  '{"destination":{"name":"Atlanta, GA"},"start_date":"2026-05-01","end_date":"2026-05-03","group_members":[{"name":"Parent","type":"adult"},{"name":"Student","type":"child","age":17}],"budget_level":"mid","vibes":["culture","food"],"travel_theme":"college-tour"}'::jsonb,
  '{"title":"Emory Campus Tour: Atlanta & Southern Charm","days":[
    {"id":"day-1","trip_id":"t","date":"2026-05-01","day_number":1,"title":"Emory Campus & Druid Hills","slots":[
      {"id":"s-1-1","day_id":"day-1","slot_type":"morning","status":"open","options":[
        {"id":"o-1-1-1","slot_id":"s-1-1","title":"Official Emory Campus Tour","description":"Student-led tour — the Quad, Michael C. Carlos Museum, Candler Library, and the Woodruff PE Center.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":90,"location":{"name":"Emory University campus"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"Emory''s tree-covered campus in the Druid Hills neighborhood is stunning"},
        {"id":"o-1-1-2","slot_id":"s-1-1","title":"Coffee at Land of a Thousand Hills","description":"Emory students'' favorite coffee shop — just off campus, good vibes, strong espresso.","category":"food","estimated_cost_per_person":5,"duration_minutes":20,"location":{"name":"Land of a Thousand Hills, Emory Village"},"weather_sensitivity":"indoor","ai_generated":true,"why_this_fits":"Where Emory students study and caffeinate"}]},
      {"id":"s-1-2","day_id":"day-1","slot_type":"afternoon","status":"open","options":[
        {"id":"o-1-2-1","slot_id":"s-1-2","title":"Georgia Tech Side Trip (20 min)","description":"Drive to Midtown Atlanta to see Georgia Tech — Tech Tower, Bobby Dodd Stadium, engineering focus.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":120,"location":{"name":"Georgia Tech, Midtown Atlanta"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"If considering STEM, Georgia Tech is 20 minutes from Emory"},
        {"id":"o-1-2-2","slot_id":"s-1-2","title":"CDC Museum (David J. Sencer)","description":"Free museum at the Centers for Disease Control — adjacent to Emory, unique to Atlanta.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":60,"location":{"name":"CDC Museum, Druid Hills"},"weather_sensitivity":"indoor","ai_generated":true,"why_this_fits":"The CDC is literally next to Emory — great for pre-med students"}]},
      {"id":"s-1-3","day_id":"day-1","slot_type":"evening","status":"open","options":[
        {"id":"o-1-3-1","slot_id":"s-1-3","title":"Dinner at Ponce City Market","description":"Atlanta''s coolest food hall in a former Sears building — The Roof has skyline views.","category":"food","estimated_cost_per_person":20,"duration_minutes":90,"location":{"name":"Ponce City Market, Beltline"},"weather_sensitivity":"either","ai_generated":true,"why_this_fits":"The best food hall in the Southeast"},
        {"id":"o-1-3-2","slot_id":"s-1-3","title":"Atlanta Beltline Walk","description":"2.4-mile trail from Ponce City Market to Krog Street Market — murals, restaurants, and city views.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":60,"location":{"name":"Atlanta Beltline Eastside Trail"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"Atlanta''s best outdoor attraction — perfect evening walk"}]}
    ]}],"hiddenGems":[{"day_number":1,"tip":"Emory''s Michael C. Carlos Museum has an actual Egyptian mummy and ancient Greek artifacts — free for students, and one of the best university museums in the US.","location":"Carlos Museum, Emory"}]}'::jsonb,
  'VYBR', uid, true, 'public', 'Weekend Emory campus tour: Druid Hills campus, Georgia Tech side trip, CDC Museum, Ponce City Market, and the Beltline.',
  ARRAY['emory', 'emory-university', 'atlanta', 'georgia', 'college', 'college-tour', 'campus', 'georgia-tech']
);

-- 6. Colgate University (Hamilton, NY)
INSERT INTO trips (title, destination, start_date, end_date, passcode, form_data, itinerary_data, created_by, user_id, is_published, visibility, description, tags) VALUES (
  'Colgate Tour: Small Town, Big Campus', 'Hamilton, NY', '2026-05-08', '2026-05-10', '1234',
  '{"destination":{"name":"Hamilton, NY"},"start_date":"2026-05-08","end_date":"2026-05-10","group_members":[{"name":"Parent","type":"adult"},{"name":"Student","type":"child","age":17}],"budget_level":"mid","vibes":["nature","culture"],"travel_theme":"college-tour"}'::jsonb,
  '{"title":"Colgate Tour: Small Town, Big Campus","days":[
    {"id":"day-1","trip_id":"t","date":"2026-05-08","day_number":1,"title":"Colgate Campus & Hamilton","slots":[
      {"id":"s-1-1","day_id":"day-1","slot_type":"morning","status":"open","options":[
        {"id":"o-1-1-1","slot_id":"s-1-1","title":"Official Colgate Campus Tour","description":"Walk the iconic hilltop campus — the Chapel, Taylor Lake, Picker Art Gallery, and the Willow Path.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":90,"location":{"name":"Colgate University, Hamilton"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"One of the most beautiful small college campuses in America — rolling hills, a chapel, and a lake"},
        {"id":"o-1-1-2","slot_id":"s-1-1","title":"The Colgate Inn Breakfast","description":"Classic New England inn restaurant — pancakes, omelets, and the campus view from the porch.","category":"food","estimated_cost_per_person":14,"duration_minutes":30,"location":{"name":"The Colgate Inn"},"weather_sensitivity":"indoor","ai_generated":true,"why_this_fits":"The social center of Hamilton — where parents and students meet"}]},
      {"id":"s-1-2","day_id":"day-1","slot_type":"afternoon","status":"open","options":[
        {"id":"o-1-2-1","slot_id":"s-1-2","title":"Hamilton Village Walk","description":"Tiny village of 4,000 — independent bookstore, Colgate Bookstore, Palace Theater, and local shops.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":60,"location":{"name":"Village of Hamilton"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"This IS the college town — Colgate is the town"},
        {"id":"o-1-2-2","slot_id":"s-1-2","title":"Syracuse University Side Trip (45 min)","description":"Drive to Syracuse for a larger university comparison — the Carrier Dome, Marshall Street, and the Quad.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":150,"location":{"name":"Syracuse University"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"Compare intimate Colgate with big-university Syracuse"}]},
      {"id":"s-1-3","day_id":"day-1","slot_type":"evening","status":"open","options":[
        {"id":"o-1-3-1","slot_id":"s-1-3","title":"Dinner at Village Tavern","description":"Hamilton''s beloved restaurant — burgers, craft beer, and the Colgate student scene.","category":"food","estimated_cost_per_person":18,"duration_minutes":60,"location":{"name":"Village Tavern, Hamilton"},"weather_sensitivity":"indoor","ai_generated":true,"why_this_fits":"Where everyone in Hamilton eats — town and gown together"},
        {"id":"o-1-3-2","slot_id":"s-1-3","title":"Taylor Lake Sunset Walk","description":"Walk around the campus lake at golden hour — peaceful, beautiful, and quintessentially Colgate.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":30,"location":{"name":"Taylor Lake, Colgate"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"The view that sells Colgate to every prospective student"}]}
    ]}],"hiddenGems":[{"day_number":1,"tip":"Walk the Willow Path — a hidden trail behind the Colgate Inn that''s beautiful in spring with blooming trees.","location":"Willow Path, Colgate"}]}'::jsonb,
  'VYBR', uid, true, 'public', 'Weekend Colgate campus tour: Hilltop campus, Taylor Lake, Hamilton village, and Syracuse University side trip.',
  ARRAY['colgate', 'colgate-university', 'hamilton', 'new-york', 'college', 'college-tour', 'campus', 'syracuse']
);

-- 7. Carnegie Mellon University (Pittsburgh)
INSERT INTO trips (title, destination, start_date, end_date, passcode, form_data, itinerary_data, created_by, user_id, is_published, visibility, description, tags) VALUES (
  'CMU Campus Tour: Tech, Art & Steel City', 'Pittsburgh, PA', '2026-05-15', '2026-05-17', '1234',
  '{"destination":{"name":"Pittsburgh, PA"},"start_date":"2026-05-15","end_date":"2026-05-17","group_members":[{"name":"Parent","type":"adult"},{"name":"Student","type":"child","age":17}],"budget_level":"mid","vibes":["culture","food"],"travel_theme":"college-tour"}'::jsonb,
  '{"title":"CMU Campus Tour: Tech, Art & Steel City","days":[
    {"id":"day-1","trip_id":"t","date":"2026-05-15","day_number":1,"title":"CMU Campus & Oakland","slots":[
      {"id":"s-1-1","day_id":"day-1","slot_type":"morning","status":"open","options":[
        {"id":"o-1-1-1","slot_id":"s-1-1","title":"Official CMU Campus Tour","description":"Tour the Oakland campus — The Cut, Hamerschlag Hall (engineering), Gates Center (CS), and the College of Fine Arts.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":90,"location":{"name":"Carnegie Mellon University"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"CMU is where tech meets art — unique combination of engineering, CS, drama, and design"},
        {"id":"o-1-1-2","slot_id":"s-1-1","title":"Coffee at Crazy Mocha","description":"Pittsburgh indie chain — campus location is always packed with CS students.","category":"food","estimated_cost_per_person":5,"duration_minutes":15,"location":{"name":"Crazy Mocha, CMU"},"weather_sensitivity":"indoor","ai_generated":true,"why_this_fits":"Fuel up like a CMU student — coffee is a CS major''s best friend"}]},
      {"id":"s-1-2","day_id":"day-1","slot_type":"afternoon","status":"open","options":[
        {"id":"o-1-2-1","slot_id":"s-1-2","title":"University of Pittsburgh (Next Door)","description":"Pitt''s campus is literally adjacent — Cathedral of Learning (42 floors), Nationality Rooms tour.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":90,"location":{"name":"University of Pittsburgh"},"weather_sensitivity":"indoor","ai_generated":true,"why_this_fits":"CMU and Pitt share a neighborhood — see both in one afternoon"},
        {"id":"o-1-2-2","slot_id":"s-1-2","title":"Andy Warhol Museum","description":"7 floors dedicated to Pittsburgh''s most famous artist — the largest single-artist museum in the US.","category":"attraction","estimated_cost_per_person":20,"duration_minutes":90,"location":{"name":"Andy Warhol Museum, North Shore"},"weather_sensitivity":"indoor","ai_generated":true,"why_this_fits":"CMU''s art school is world-class — Warhol is the proof"}]},
      {"id":"s-1-3","day_id":"day-1","slot_type":"evening","status":"open","options":[
        {"id":"o-1-3-1","slot_id":"s-1-3","title":"Dinner in Squirrel Hill","description":"Pittsburgh''s diverse food neighborhood — Sichuan at Chengdu Gourmet, pierogies at S&D Polish Deli.","category":"food","estimated_cost_per_person":15,"duration_minutes":60,"location":{"name":"Squirrel Hill, Murray Ave"},"weather_sensitivity":"indoor","ai_generated":true,"why_this_fits":"Where CMU students eat off campus — diverse and affordable"},
        {"id":"o-1-3-2","slot_id":"s-1-3","title":"Primanti Bros Sandwich","description":"Pittsburgh''s iconic sandwich — meat, coleslaw, fries, all between two slices of bread.","category":"food","estimated_cost_per_person":12,"duration_minutes":20,"location":{"name":"Primanti Bros, Strip District"},"weather_sensitivity":"indoor","ai_generated":true,"why_this_fits":"You can''t visit Pittsburgh without a Primanti''s sandwich"}]}
    ]}],"hiddenGems":[{"day_number":1,"tip":"CMU''s Fence on The Cut is painted by student organizations every night — whatever''s on it when you visit tells you what''s happening on campus.","location":"The Fence, CMU"}]}'::jsonb,
  'VYBR', uid, true, 'public', 'Weekend CMU campus tour: Tech and art, University of Pittsburgh next door, Andy Warhol Museum, and Pittsburgh food.',
  ARRAY['cmu', 'carnegie-mellon', 'pittsburgh', 'pennsylvania', 'college', 'college-tour', 'campus', 'pitt', 'tech']
);

-- 8. Colorado School of Mines (Golden)
INSERT INTO trips (title, destination, start_date, end_date, passcode, form_data, itinerary_data, created_by, user_id, is_published, visibility, description, tags) VALUES (
  'Mines Campus Tour: Engineering & Mountains', 'Golden, CO', '2026-05-22', '2026-05-24', '1234',
  '{"destination":{"name":"Golden, CO"},"start_date":"2026-05-22","end_date":"2026-05-24","group_members":[{"name":"Parent","type":"adult"},{"name":"Student","type":"child","age":17}],"budget_level":"mid","vibes":["adventure","nature"],"travel_theme":"college-tour"}'::jsonb,
  '{"title":"Mines Campus Tour: Engineering & Mountains","days":[
    {"id":"day-1","trip_id":"t","date":"2026-05-22","day_number":1,"title":"Mines Campus & Golden","slots":[
      {"id":"s-1-1","day_id":"day-1","slot_type":"morning","status":"open","options":[
        {"id":"o-1-1-1","slot_id":"s-1-1","title":"Official Colorado School of Mines Tour","description":"Campus tour — Coolbaugh Hall, Green Center, the Geology Museum with gems and minerals, and Kafadar Commons.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":90,"location":{"name":"Colorado School of Mines, Golden"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"One of the top engineering schools in the US, nestled against the Rockies"},
        {"id":"o-1-1-2","slot_id":"s-1-1","title":"Breakfast at Table Mountain Inn","description":"Western-themed inn with a sunny patio — huevos rancheros, mountain views, and strong coffee.","category":"food","estimated_cost_per_person":14,"duration_minutes":30,"location":{"name":"Table Mountain Inn, Golden"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"Start the day with Rockies views from the patio"}]},
      {"id":"s-1-2","day_id":"day-1","slot_type":"afternoon","status":"open","options":[
        {"id":"o-1-2-1","slot_id":"s-1-2","title":"Geology Museum & M Climb","description":"Free geology museum with meteorites, gems, and fossils — then hike the M trail to the giant letter M on Mt. Zion.","category":"adventure","estimated_cost_per_person":0,"duration_minutes":120,"location":{"name":"Geology Museum / Mt. Zion M Trail"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"The M hike is a Mines tradition — every freshman does it during orientation"},
        {"id":"o-1-2-2","slot_id":"s-1-2","title":"Coors Brewery Tour (Free)","description":"World''s largest single-site brewery is in Golden — free tour, free beer at the end.","category":"food","estimated_cost_per_person":0,"duration_minutes":60,"location":{"name":"Coors Brewery, Golden"},"weather_sensitivity":"indoor","ai_generated":true,"why_this_fits":"Free beer at the foot of the Rockies — parents appreciate this one"}]},
      {"id":"s-1-3","day_id":"day-1","slot_type":"evening","status":"open","options":[
        {"id":"o-1-3-1","slot_id":"s-1-3","title":"Dinner at Woody''s Wood Fired Pizza","description":"Golden''s favorite pizza — wood-fired pies on the Clear Creek patio with mountain views.","category":"food","estimated_cost_per_person":16,"duration_minutes":45,"location":{"name":"Woody''s, Golden"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"Pizza by the creek — Golden''s most beloved restaurant"},
        {"id":"o-1-3-2","slot_id":"s-1-3","title":"CU Boulder Side Trip (30 min)","description":"Quick drive to Boulder to compare Mines with CU — larger campus, different vibe, same mountains.","category":"attraction","estimated_cost_per_person":0,"duration_minutes":90,"location":{"name":"CU Boulder"},"weather_sensitivity":"outdoor","ai_generated":true,"why_this_fits":"Mines vs CU Boulder is a common comparison — see both"}]}
    ]}],"hiddenGems":[{"day_number":1,"tip":"Clear Creek runs right through Golden — in summer, students tube down it between classes. In spring, watch kayakers on the whitewater course.","location":"Clear Creek, Golden"}]}'::jsonb,
  'VYBR', uid, true, 'public', 'Weekend Colorado School of Mines tour: Engineering campus, Geology Museum, M Trail hike, Coors Brewery, and CU Boulder side trip.',
  ARRAY['mines', 'colorado-school-of-mines', 'golden', 'colorado', 'college', 'college-tour', 'campus', 'engineering', 'cu-boulder']
);

RAISE NOTICE 'All 8 college tour trips inserted';
END $$;
